### PR TITLE
add pdm, formatter, logger and linters checking

### PR DESCRIPTION
**Pull request by RomanOdobesku**

### CODE REVIEW

**Review by sanonesan — COMMENTED** [review]
cool

**Review by temochka2005 — APPROVED** [review]
checked

**Comment by sanonesan** [comment]
checked

**Review by liaaana — APPROVED** [review]
amazing❣️

**Review by sanonesan — APPROVED** [review]
cool

**Review by Mitya11 — APPROVED** [review]
nice

**Review by tretyakov3112 — APPROVED** [review]
very cool

**Review by everzakov — APPROVED** [review]

**Pull request merged**
